obj-$(CONFIG_NTL_PHC) += ntl_phc/
obj-$(CONFIG_NTL_MACB) += ntl_macb/
obj-$(CONFIG_NTL_STS) += ntl_sts/
obj-$(CONFIG_NTL_SGN) += ntl_sgn/
obj-$(CONFIG_NTL_FGN) += ntl_fgn/
obj-$(CONFIG_NTL_CTS) += ntl_cts/